### ISSUE TITLE
Multithreading does not work on OSX

### ISSUE THREAD

**Issue by amalmurali47** [codingo/Interlace#36]
Hi,

When I run like Interlace like this:

    interlace -tL targets.txt -threads 20 -c "dirsearch -u _target_ -t 30 -e '' -w wordlist.txt > results.txt" -v

It feels more like:

    while read target; do dirsearch [args] > output.txt; done < targets.txt

It seems to run everything sequentially. @hakluke confirms that he also faced the same issue.

**Comment by ProDigySML** [comment]
Thanks for that! Trying to get my hands on a Mac to test this issue.

**Comment by hakluke** [comment]
Hey @amalmurali47 - thanks for making the issue. I did have the same issue on mac so it seems to be OSX related. Unfortunately I also no longer have a mac to test on. 

Do you think you could just paste the output of the following as proof + testbench?

```
seq 1 5 > ./test.txt
time interlace -tL ./test.txt -threads 5 -c "sleep _target_"
```

**Comment by xYantix** [comment]
I have a Macbook. Testing isn't working properly for me tonight. Will try again tomorrow and let you know how I go!

**Comment by xYantix** [comment]
<img width="794" alt="Interlace" src="https://user-images.githubusercontent.com/3001014/56464665-ca766a80-6420-11e9-8a98-495219b3fab7.png">
`xYantixs-MacBook-Pro:Interlace xyantix$ seq 1 5 > ./test.txt
xYantixs-MacBook-Pro:Interlace xyantix$ time python interlace.py -tL ./test.txt -threads 5 -c "sleep _target_"
==============================================
Interlace v1.3.4	by Michael Skelton (@codingo_)
==============================================
[10:28:09] [THREAD] [sleep 4] Added to Queue 
[10:28:09] [THREAD] [sleep 5] Added to Queue 
[10:28:09] [THREAD] [sleep 2] Added to Queue 
[10:28:09] [THREAD] [sleep 3] Added to Queue 
[10:28:09] [THREAD] [sleep 1] Added to Queue 


real	0m15.236s
user 0m0.055s
sys	0m0.083s`

Added a picture because the formatting was funky. Looks single threaded though.

**Comment by ProDigySML** [comment]
Awesome! Thanks mate! I'll try to debug what the issue is.

**Comment by xYantix** [comment]
No worries. Let me know if you need any help with testing. Catch me on here
or on the SecTalks Slack :)

**Comment by amalmurali47** [comment]
@hakluke: Sure. Here's the output on my machine:

```
➜ seq 1 5 > ./test.txt
➜ time interlace -tL ./test.txt -threads 5 -c "sleep _target_"
==============================================
Interlace v1.3.3	by Michael Skelton (@codingo_)
==============================================
[13:52:39] [THREAD] [sleep 4] Added to Queue
[13:52:39] [THREAD] [sleep 5] Added to Queue
[13:52:39] [THREAD] [sleep 2] Added to Queue
[13:52:39] [THREAD] [sleep 3] Added to Queue
[13:52:39] [THREAD] [sleep 1] Added to Queue
interlace -tL ./test.txt -threads 5 -c "sleep _target_"  
0.17s user 
0.09s system 
1% cpu 
15.278 total
```

**Comment by Emxm3** [comment]
Using xYantix's macbook and confirmation from he himself, we've fixed the issue with the multi-threading on OSX.

**Comment by Emxm3** [comment]
(Yay, my first pull request evarrrr!)

**Comment by hakluke** [comment]
Phwoar nice work dudes!

**Comment by xYantix** [comment]
<img width="575" alt="Interlace" src="https://user-images.githubusercontent.com/3001014/56956035-8e0be280-6b75-11e9-8661-9701b40b7c18.png">

Working nicely on my machine now! Mac OS 10.14.3
