### ISSUE TITLE
Interlace spawns a large number of threads (>5), even with -threads option set low

### ISSUE THREAD

**Issue by br-sn** [codingo/Interlace#87]
I demonstrated this to @prodigysml in private and cannot show the screenshots due to the sensitive nature. 

Interlace seems to spawn a thread for every target in the list rather than the default of 5 or the number specified via the '-threads' argument.

**Comment by iamOgunyinka** [comment]
It would be really helpful if you could produce a minimum working script affected by this 'cause [this](https://github.com/codingo/Interlace/blob/d85d15a3763a1fbd856d939d221299e59ec16bab/Interlace/lib/threader.py#L96) is the part of the code that handles the thread dissemination(called from [here](https://github.com/codingo/Interlace/blob/d85d15a3763a1fbd856d939d221299e59ec16bab/Interlace/interlace.py#L26)). If you look further down that line, you'll see I used `ThreadExecutors` rather than raw threads. However, you're free to try out with
